on:
  workflow_dispatch:
    inputs:
      action:
        description: '操作'
        required: true
        default: '压测'
        type: choice
        options:
          - 远程
          - 压测
          - 停止所有
          - 删除仓库

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

run-name: '${{ inputs.action }}'

env:
  TZ: Asia/Shanghai

jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job_id: [1,2,3,4,5,6,7,8,9,10,11]
    steps:
      - uses: actions/checkout@v4
      - name: 设置环境变量
        run: |
          JOB_ID=${{ matrix.job_id }}
          ACCOUNTS='[
          [],
          ["dikoo21922","0Fc420e38C34DA8F7088","ZU2JLY4VFIANXJRX","2025-07-28 17:26:51.248"],
          ["u31derajatispanas","8e43D64D6358104d2739","QEMFK62RXGJ2JY4W","2025-07-28 17:27:03.809"],
          ["Oluwatodi1962","8af3a30C9a96a4124f3c","TEOTZOHW3JAYB6WB","2025-07-28 17:27:17.840"],
          ["swkim09114900","998d14127Ff3f0E63D83","WBFZ4X3SZX4H7VBL","2025-07-28 17:27:41.581"],
          ["Lindaherlinaa5216","Ffd25B6DBC4cd272d79A","EH4OZIWKYEHJF4D5","2025-07-28 17:25:05.965"],
          ["cepitalove1195","86591279afdd39f5e0cb","4OWT25VX22K7G6VO","2025-07-28 17:27:06.712"],
          ["Muo022025","B254606192b67BCAb397","3EJRWXZXKHJEBYOT","2025-07-28 17:27:19.079"],
          ["kanagireddy2934","7EC8a1B665Fab6Cdf633","IJE5KMF356DYN2PA","2025-07-28 17:25:52.097"],
          ["momowndut2025","F76F0e466EBA122EBD9A","TVNS7TFEJ3GL73FJ","2025-07-28 17:25:33.605"]
          ]'
          USERNAME=$(echo $ACCOUNTS | jq -r ".[$JOB_ID][0]")
          PASSWORD=$(echo $ACCOUNTS | jq -r ".[$JOB_ID][1]")
          SECRET=$(echo $ACCOUNTS | jq -r ".[$JOB_ID][2]")
          
          echo "GITHUB_USERNAME=$USERNAME" >> $GITHUB_ENV
          echo "GITHUB_PASSWORD=$PASSWORD" >> $GITHUB_ENV
          echo "GITHUB_SECRET=$SECRET" >> $GITHUB_ENV

          yarn
          yarn build

      - name: 远程
        if: ${{ inputs.action == '远程' }}
        env:
          REMOTE: true
        run: | 
          node dist/app.js

      - name: 压测
        if: ${{ inputs.action == '压测' }}
        env:
          STRESS_TEST: true
        run: | 
          node dist/app.js

      - name: 停止所有
        if: ${{ inputs.action == '停止所有' }}
        env:
          Stop_All_PIPELINES: true
        run: | 
          node dist/app.js

      - name: 删除仓库
        if: ${{ inputs.action == '删除仓库' }}
        env:
          # DELETE_REPO: true
          UPDATE_REPO: true
        run: | 
          node dist/app.js
