on:
  workflow_dispatch:
    inputs:
      action:
        description: '操作'
        required: true
        default: '压测'
        type: choice
        options:
          - 远程
          - 压测
          - 停止所有
          - 删除仓库

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

run-name: '${{ inputs.action }}'

env:
  TZ: Asia/Shanghai

jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job_id: [1,2,3,4,5,6,7,8,9,10,11]
    steps:
      - uses: actions/checkout@v4
      - name: 设置环境变量
        run: |
          JOB_ID=${{ matrix.job_id }}
          ACCOUNTS='[
            [],
            ["Hamednkj4581","1Af970bf0254DB8AC29b","T6G5YN6GAMWGL7MR"],
            ["boskomaaerrozz8632","c23681334512F47b201c","NAYSWBF4USNV754F"],
            ["Rauno1232025","8DE160d47642da589f34","X3LI2J7WOB4HSERT"],
            ["PJHSDiNa1492","30A413a9FcAd495e4556","322U3YENBS3RIXSZ"],
            ["freyakailing6746","483F3Dd38c8EAa15162a","TH6ECMH5K2RTBCDO"],
            ["Senka301919","145eCF5a7C3733A897cE","3XU6MZR44F4OEXHG"],
            ["Arreaga102025@outlook.com","8D0deb64E33Dcd3cAf24","QF3SIBWEGVUAY327"]
          ]'
          USERNAME=$(echo $ACCOUNTS | jq -r ".[$JOB_ID][0]")
          PASSWORD=$(echo $ACCOUNTS | jq -r ".[$JOB_ID][1]")
          SECRET=$(echo $ACCOUNTS | jq -r ".[$JOB_ID][2]")
          
          echo "GITHUB_USERNAME=$USERNAME" >> $GITHUB_ENV
          echo "GITHUB_PASSWORD=$PASSWORD" >> $GITHUB_ENV
          echo "GITHUB_SECRET=$SECRET" >> $GITHUB_ENV

          yarn
          yarn build

      - name: 远程
        if: ${{ inputs.action == '远程' }}
        env:
          REMOTE: true
        run: | 
          node dist/app.js

      - name: 压测
        if: ${{ inputs.action == '压测' }}
        env:
          STRESS_TEST: true
        run: | 
          node dist/app.js

      - name: 停止所有
        if: ${{ inputs.action == '停止所有' }}
        env:
          Stop_All_PIPELINES: true
        run: | 
          node dist/app.js

      - name: 删除仓库
        if: ${{ inputs.action == '删除仓库' }}
        env:
          # DELETE_REPO: true
          UPDATE_REPO: true
        run: | 
          node dist/app.js
