on:
  workflow_dispatch:
    inputs:
      action:
        description: '操作'
        required: true
        default: '压测'
        type: choice
        options:
          - 远程
          - 压测
          - 停止所有
          - 删除仓库

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

run-name: '${{ inputs.action }}'

env:
  TZ: Asia/Shanghai

jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      # max-parallel: 5
      fail-fast: false
      matrix:
        job_id: [0,1,2,3,4,5,6,7,8,9,10,11,12]
    steps:
      - uses: actions/checkout@v4
      - name: 设置环境变量
        run: |
          JOB_ID=${{ matrix.job_id }}
          ACCOUNTS='[
          [
          "Yeison20051919",
          "2367DAaB915125e7C4c1",
          "HLP75TG6C4MWDICB",
          "2025-07-28 20:31:33.407"
          ],
          [
          "sinkooooon8837",
          "78118824a5D3F0c67389",
          "A6KDZHCDAHYLO2OP",
          "2025-07-28 20:31:19.777"
          ],
          [
          "Unvy74656",
          "96eF1e7635307dc5f0A4",
          "NYAU7VTJPSSYDNIR",
          "2025-07-28 20:32:10.269"
          ],
          [
          "Natureholder6387",
          "360CAc0Cd78477e75E63",
          "3GKLBS5PWUOS4ZRK",
          "2025-07-28 20:31:39.118"
          ],
          [
          "OksankaLukianovets311",
          "D4CC28997aAebbf36209",
          "NTOGLQC7GR4ABL5J",
          "2025-07-28 20:31:39.043"
          ],
          [
          "SarMack137621",
          "D3a3736F9cEb7c917989",
          "WYEGW6LW6TOOODGQ",
          "2025-07-28 20:31:15.117"
          ],
          [
          "AryanSinghalOfficial9177",
          "8D15BDd9abec2d4f91d8",
          "UIPVW2B6GEXB63WS",
          "2025-07-28 20:31:23.470"
          ],
          [
          "Anima-OS-Dev292",
          "4659025758f06765dC43",
          "ZZUC6HWBLUQ25LOG",
          "2025-07-28 20:31:29.956"
          ],
          
          ["Oluwatodi1962","8af3a30C9a96a4124f3c","TEOTZOHW3JAYB6WB","2025-07-28 17:27:17.840"],
          
          ["cepitalove1195","86591279afdd39f5e0cb","4OWT25VX22K7G6VO","2025-07-28 17:27:06.712"],
          
          [
          "DaniAnie2575",
          "9b0Eb30541A14a014f7f",
          "5OJXX32CGU3R4PDX",
          "2025-07-28 19:01:57.134"
          ],
          
          [
          "grggagandin117578",
          "AbEa88058bd060CAc2cC",
          "QNUVMX345RW7CL4Y",
          "2025-07-28 19:01:44.404"
          ],
          [
          "Dhiabxkwjxkssl3274",
          "3a636f0cA3de9914e851",
          "LQWOKFSPQLF2IZMW",
          "2025-07-28 19:01:49.670"
          ]
          ]'

          LEN=$(echo $ACCOUNTS | jq 'length')
          if [ "$JOB_ID" -ge "$LEN" ]; then
            echo "JOB_ID 超出范围，直接退出"
            exit 1
          fi

          USERNAME=$(echo $ACCOUNTS | jq -r ".[$JOB_ID][0]")
          PASSWORD=$(echo $ACCOUNTS | jq -r ".[$JOB_ID][1]")
          SECRET=$(echo $ACCOUNTS | jq -r ".[$JOB_ID][2]")
          
          echo "GITHUB_USERNAME=$USERNAME" >> $GITHUB_ENV
          echo "GITHUB_PASSWORD=$PASSWORD" >> $GITHUB_ENV
          echo "GITHUB_SECRET=$SECRET" >> $GITHUB_ENV

          yarn
          yarn build

      - name: 远程
        if: ${{ inputs.action == '远程' }}
        env:
          REMOTE: true
        run: | 
          node dist/app.js

      - name: 压测
        if: ${{ inputs.action == '压测' }}
        env:
          STRESS_TEST: true
        run: | 
          node dist/app.js

      - name: 停止所有
        if: ${{ inputs.action == '停止所有' }}
        env:
          Stop_All_PIPELINES: true
        run: | 
          node dist/app.js

      - name: 删除仓库
        if: ${{ inputs.action == '删除仓库' }}
        env:
          DELETE_REPO: true
          UPDATE_REPO: true
        run: | 
          node dist/app.js
