on:
  workflow_dispatch:
    inputs:
      action:
        description: '操作'
        required: true
        default: '压测'
        type: choice
        options:
          - 远程
          - 压测
          - 停止所有
          - 删除仓库

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

run-name: '${{ inputs.action }}'

env:
  TZ: Asia/Shanghai

jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      # max-parallel: 5
      fail-fast: false
      matrix:
        job_id: [0,1,2,3,4,5,6,7,8,9]
    steps:
      - uses: actions/checkout@v4
      - name: 设置环境变量
        run: |
          JOB_ID=${{ matrix.job_id }}
          ACCOUNTS='[
          [
          "Keliana-spec2968",
          "5BeC40d19A66eAE62a1B",
          "DXNJKAV427ZAXEUH",
          "2025-07-29 14:09:37.198"
          ],
          [
          "u1717171717171717171717",
          "De63aEC9194b10e255CA",
          "3WIB3BEOPWMFIHSF",
          "2025-07-29 14:13:24.419"
          ],
          [
          "suraj979854624",
          "669888f0EEE7F7DD64CD",
          "SFF6JYP6X7LQ5FSG",
          "2025-07-29 14:12:16.302"
          ],
          [
          "klochanola1261",
          "0c6c7fC86b3eDD6ABCCE",
          "LMTRAWOBTXBAR3GL",
          "2025-07-29 14:09:46.379"
          ],
          [
          "nicocappai6864",
          "A754D5c656333E005f8C",
          "CMECRN5QKVSSMUT3",
          "2025-07-29 14:10:15.957"
          ],
          [
          "Noroall8192",
          "E866BF4bdB12AF09beac",
          "VOGFTXL6IYB5EPAA",
          "2025-07-29 14:09:39.391"
          ],
          [
          "thingprog8508",
          "436a3CA1CD14eA7152b7",
          "TBWGNICU2DL6LPHB",
          "2025-07-29 14:13:12.613"
          ],
          [
          "Astraler31356",
          "0aB9D04FC03CF68a8E0c",
          "JXAHF4BFBZPM75QR",
          "2025-07-29 14:09:36.673"
          ],
          [
          "Lima2109102623",
          "a0E77C8BD974280A93e2",
          "OED5RYP5M6Z74URB",
          "2025-07-29 14:13:06.301"
          ],
          [
          "ayeshasmartzone8086",
          "C5150bd6f794Fd031826",
          "CGGXX4R2T45QE2Z2",
          "2025-07-29 14:12:19.365"
          ],
          [
          "Yeison20051919",
          "2367DAaB915125e7C4c1",
          "HLP75TG6C4MWDICB",
          "2025-07-28 20:31:33.407"
          ],
          [
          "sinkooooon8837",
          "78118824a5D3F0c67389",
          "A6KDZHCDAHYLO2OP",
          "2025-07-28 20:31:19.777"
          ],
          [
          "Unvy74656",
          "96eF1e7635307dc5f0A4",
          "NYAU7VTJPSSYDNIR",
          "2025-07-28 20:32:10.269"
          ],
          [
          "Natureholder6387",
          "360CAc0Cd78477e75E63",
          "3GKLBS5PWUOS4ZRK",
          "2025-07-28 20:31:39.118"
          ],
          [
          "OksankaLukianovets311",
          "D4CC28997aAebbf36209",
          "NTOGLQC7GR4ABL5J",
          "2025-07-28 20:31:39.043"
          ],
          [
          "SarMack137621",
          "D3a3736F9cEb7c917989",
          "WYEGW6LW6TOOODGQ",
          "2025-07-28 20:31:15.117"
          ],
          [
          "AryanSinghalOfficial9177",
          "8D15BDd9abec2d4f91d8",
          "UIPVW2B6GEXB63WS",
          "2025-07-28 20:31:23.470"
          ],
          [
          "Anima-OS-Dev292",
          "4659025758f06765dC43",
          "ZZUC6HWBLUQ25LOG",
          "2025-07-28 20:31:29.956"
          ],
          
          ["Oluwatodi1962","8af3a30C9a96a4124f3c","TEOTZOHW3JAYB6WB","2025-07-28 17:27:17.840"],
          
          ["cepitalove1195","86591279afdd39f5e0cb","4OWT25VX22K7G6VO","2025-07-28 17:27:06.712"],
          
          [
          "DaniAnie2575",
          "9b0Eb30541A14a014f7f",
          "5OJXX32CGU3R4PDX",
          "2025-07-28 19:01:57.134"
          ],
          
          [
          "grggagandin117578",
          "AbEa88058bd060CAc2cC",
          "QNUVMX345RW7CL4Y",
          "2025-07-28 19:01:44.404"
          ],
          [
          "Dhiabxkwjxkssl3274",
          "3a636f0cA3de9914e851",
          "LQWOKFSPQLF2IZMW",
          "2025-07-28 19:01:49.670"
          ]
          ]'

          LEN=$(echo $ACCOUNTS | jq 'length')
          if [ "$JOB_ID" -ge "$LEN" ]; then
            echo "JOB_ID 超出范围，直接退出"
            exit 1
          fi

          USERNAME=$(echo $ACCOUNTS | jq -r ".[$JOB_ID][0]")
          PASSWORD=$(echo $ACCOUNTS | jq -r ".[$JOB_ID][1]")
          SECRET=$(echo $ACCOUNTS | jq -r ".[$JOB_ID][2]")
          
          echo "GITHUB_USERNAME=$USERNAME" >> $GITHUB_ENV
          echo "GITHUB_PASSWORD=$PASSWORD" >> $GITHUB_ENV
          echo "GITHUB_SECRET=$SECRET" >> $GITHUB_ENV

          yarn
          yarn build

      - name: 远程
        if: ${{ inputs.action == '远程' }}
        env:
          REMOTE: true
        run: | 
          node dist/app.js

      - name: 压测
        if: ${{ inputs.action == '压测' }}
        env:
          STRESS_TEST: true
        run: | 
          node dist/app.js

      - name: 停止所有
        if: ${{ inputs.action == '停止所有' }}
        env:
          Stop_All_PIPELINES: true
        run: | 
          node dist/app.js

      - name: 删除仓库
        if: ${{ inputs.action == '删除仓库' }}
        env:
          DELETE_REPO: true
          UPDATE_REPO: true
        run: | 
          node dist/app.js
