on:
  workflow_dispatch:
    inputs:
      action:
        description: '操作'
        required: true
        default: '压测'
        type: choice
        options:
          - 远程
          - 压测
          - 停止所有
          - 删除仓库

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

run-name: '${{ inputs.action }}'

env:
  TZ: Asia/Shanghai

jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      # max-parallel: 5
      fail-fast: false
      matrix:
        job_id: [0,1,2,3,4,5,6,7,8,9]
    steps:
      - uses: actions/checkout@v4
      - name: 设置环境变量
        run: |
          JOB_ID=${{ matrix.job_id }}
          ACCOUNTS='[

          [
          "nahuelamar3949",
          "C079e18970eAc9bCa1C1",
          "ZXQYF5LVLB7ECWWY",
          "2025-07-29 19:20:57.904"
          ],
          [
          "giit1217366",
          "3f10FBDF9fcE1a126D30",
          "J4CGSNXFOM3FDOJD",
          "2025-07-29 19:20:35.527"
          ],
          [
          "Fatima0422021",
          "562128FA7b55939d76b1",
          "AZAHA2PZUUMDETAD",
          "2025-07-29 19:20:57.895"
          ],
          [
          "ZOBIGULL9986",
          "71F57b3471DeEfb72116",
          "YUCHRBX6UVM223HA",
          "2025-07-29 19:21:25.728"
          ],
          [
          "bhimesh112025",
          "464902D9398b77995133",
          "PDLRU7XBJA7EE7PD",
          "2025-07-29 19:21:04.181"
          ],
          [
          "AnimatedMannequin6461",
          "7aB505CeB2F048EbFf1B",
          "IT2NHCML54ONU7YY",
          "2025-07-29 19:20:58.613"
          ],
          [
          "MaVi14062025",
          "8659f8A5CC0f917b0802",
          "DWISYMCEOKOUP6J5",
          "2025-07-29 19:22:20.844"
          ],
          [
          "fgirweu2190",
          "4148C19810588230e2b6",
          "NAUQ4RSBPCTKMPXG",
          "2025-07-29 19:23:02.794"
          ],
          [
          "KTPPUz7061",
          "6404014D25B84A3a6574",
          "JKO4G6LRU7LN45OP",
          "2025-07-29 19:20:57.933"
          ],
          [
          "hub-of-islam4718",
          "45aAD4615C5a1202B78e",
          "KCWLPADT4ICZMN24",
          "2025-07-29 19:20:57.225"
          ],
          
          [
          "rbravoCLA1352",
          "5Cd56B3ca8855A841Fca",
          "QPX3XWE5JCSHF356",
          "2025-07-29 18:32:14.786"
          ],
          [
          "Kinetibeb2016",
          "9a3521ddB6B113E68624",
          "PIFG5NXT3GLAWLMV",
          "2025-07-29 18:31:29.265"
          ],
          [
          "Mywisdomteeth8130",
          "21baa31d52db578610F3",
          "FTVPK64BHY2BWR23",
          "2025-07-29 18:32:03.770"
          ],
          [
          "Ken23542025",
          "72C51DC632a48CB6a762",
          "OLOFKEYSI4IBAI3M",
          "2025-07-29 18:31:50.649"
          ],
          [
          "uhtred-ragnarson-rgb9443",
          "60e6cfEb69C98Af6d0eF",
          "SIA5ZQASQCWGMLPH",
          "2025-07-29 18:31:34.221"
          ],
          [
          "shreyr186425",
          "85Cb7bcd34941F097e7c",
          "XSIDSYIKZDEBWG32",
          "2025-07-29 18:31:51.694"
          ],
          [
          "zhangdaanAllcam5011",
          "769770199a44850b2D9a",
          "7TFBVE3LFNXKNRYI",
          "2025-07-29 18:32:00.196"
          ],
          [
          "PairDong6723",
          "061390e29371354cD2a9",
          "VYIHTVIZFN5OLMBE",
          "2025-07-29 18:31:31.291"
          ],
          [
          "AK52777793",
          "eE9a9431312030a59a6C",
          "2GPEBLLNDDQHCFDG",
          "2025-07-29 18:31:38.102"
          ],
          [
          "Forestmist43214187",
          "C989284e608104c3ce28",
          "7NETCKVIXSONG6QO",
          "2025-07-29 18:31:37.977"
          ]
          
          ]'

          LEN=$(echo $ACCOUNTS | jq 'length')
          if [ "$JOB_ID" -ge "$LEN" ]; then
            echo "JOB_ID 超出范围，直接退出"
            exit 1
          fi

          USERNAME=$(echo $ACCOUNTS | jq -r ".[$JOB_ID][0]")
          PASSWORD=$(echo $ACCOUNTS | jq -r ".[$JOB_ID][1]")
          SECRET=$(echo $ACCOUNTS | jq -r ".[$JOB_ID][2]")
          
          echo "GITHUB_USERNAME=$USERNAME" >> $GITHUB_ENV
          echo "GITHUB_PASSWORD=$PASSWORD" >> $GITHUB_ENV
          echo "GITHUB_SECRET=$SECRET" >> $GITHUB_ENV

          status=$(curl -o /dev/null -s -w "%{http_code}" https://github.com/$USERNAME)
          if [ "$status" -eq 200 ]; then
              echo "请求成功"
          else
              echo "请求失败，状态码：$status"
              exit 1
          fi

          yarn
          yarn build

      - name: 远程
        if: ${{ inputs.action == '远程' }}
        env:
          REMOTE: true
        run: | 
          node dist/app.js

      - name: 压测
        if: ${{ inputs.action == '压测' }}
        env:
          STRESS_TEST: true
        run: | 
          node dist/app.js

      - name: 停止所有
        if: ${{ inputs.action == '停止所有' }}
        env:
          Stop_All_PIPELINES: true
        run: | 
          node dist/app.js

      - name: 删除仓库
        if: ${{ inputs.action == '删除仓库' }}
        env:
          DELETE_REPO: true
          UPDATE_REPO: true
        run: | 
          node dist/app.js
