name: 测试

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai

jobs:
  concurrent-jobs:
    runs-on: self-hosted
    strategy:
      matrix:
        job_id: [1, 2, 3, 4, 5]
    steps:
      - name: 记录时间戳
        shell: bash
        run: |
          curl ipinfo.io
          ps -p 1 -o lstart= | xargs -I{} date -d "{}" "+%Y-%m-%d %H:%M:%S"

